#cloud-config

coreos:
  update:
    reboot-strategy: "off"
  units:
  - name: etcd-member.service
    drop-ins:
      - name: 20-clct-etcd-member.conf
        content: |
          [Service]
          Environment="ETCD_IMAGE_TAG=v3.2.0"
          EnvironmentFile=/etc/environment
          ExecStart=
          ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \
            --name=%H \
            --listen-peer-urls="http://${COREOS_PRIVATE_IPV4}:2380" \
            --listen-client-urls="http://0.0.0.0:2379" \
            --initial-advertise-peer-urls="http://${COREOS_PRIVATE_IPV4}:2380" \
            --initial-cluster="%H=http://${COREOS_PRIVATE_IPV4}:2380" \
            --initial-cluster-state new \
            --advertise-client-urls="http://${COREOS_PRIVATE_IPV4}:2379"
    command: start
